### ISSUE TITLE
Cleanup WIPs

### ISSUE THREAD

**Issue by Treiblesschorle** [scijava/scijava#1]
There are some WIP commits which need to be cleaned up, verified and tested. All WIP commits involve changes to the ```Types``` utility class in order to make the improved generic type matching working.

The complete list of WIPs is the following:
<details><summary>SPOILER</summary>

| Commit | Message |
| ------- | ------ |
| d266b688aee5c13dcc9d6f23af61f0aa553e100e | WIP: Handle case where type is not parameterized but superClass is. This needs to be verified. |
| 386b525e6f76790d39474fbfb7bad055488bfafb | WIP: Add satisfies methods from scijava-common type-service branch |
| 52bff53ac7c88e3c9744e9f7077e1662dbbb8ebb | WIP: get correct type arguments if src is not parameterized itself |
| 8082964258d6caae1095115bac7d645d63bbcca0 | WIP: add toString to TypeVarInfo |
| c176f4a9484238f1bc760438bf5d8828a5dbdeac | WIP: Use the bound of the TypeVariable as search class |
| 1aaacf61a09449b6cb95794e3b35c41ea212338d | WIP: Move hack to Types utility class |
| 3fdde460d45abeefa778c6040be2bb19c768f1a3 | WIP: use Types.isAssignable to fix assignability from boxed to unboxed |
| fe12ae4e065b1907b83f3bd6713f81567f41a6db | WIP: Switch order of equals comparison |
| d4828258178fe61d2f43a8e7193716571d607df2 | WIP: Fix bug in equals method |
| 1c9d1209f48c4e32db9e55cf78282a197f396403 | WIP: Add second version of unroll method which allows to specify if type vars should be followed |
| 0fb1824d0f31e464d6eb801fb35265048ebab806 | WIP: Add methods |
| f086e2d39313878666bf2a15f3f29020bcf5be55 | WIP: Fix satisfies method for types missing type parameters |
| 730e81e9bbc15e7c86c859c8aa1cea8aa47a6b6b | WIP: add toString for capture types |
| 0a53aaa98fbfa191ab5dfaf95f2b4ca23a3e4616 | WIP: make fieldType method return type variables instead of captures |
| ca291e64144024d140de28c1cc7feb53794e25ad | WIP: Add type variables instead of wildcards |
| aa7615501847195ddbb3b0cb3e389d2cc9654902 | WIP: expose methods from GentyRef |

</details>

**Comment by gselzer** [comment]
Time commitment: 3 weeks. All of these WIPs will take time to learn about, fix, and test properly.

**Comment by gselzer** [comment]
@hinerm and I believe that because these WIPs are really old, it's probably not worth investigating anymore:
* Many of these WIPs are likely fixed already, and it would take significant time to find and merge the fixes with the WIP commits.
* Renaming these commits would basically rewrite the entire incubator commit chain, breaking previous references.
