### ISSUE TITLE
Is OpHistory preserving what we want?

### ISSUE THREAD

**Issue by hinerm** [scijava/scijava#100]
While running a `Map` operation (coarseness), I noticed that the `OpHistory` was full of keys for all the individual pixels of the operation.

However because `UnsignedByteType` has a [hashCode and equals](https://github.com/imglib/imglib2/blob/637804d514c16cda2bd02d8cc62c9458c59918d9/src/main/java/net/imglib2/type/numeric/integer/GenericByteType.java#L247-L260) that is defined by the byte *value*, the `mutationMap` is going to look more like a histogram of values, with the resulting pixels getting a number of entries equal to their frequency.

But that doesn't really tell us anything about the order things were done right? And I'm not sure what "history" really means if an op is multithreaded across each pixel in an image.

Also of note was that the [map "output" pixels](https://github.com/scijava/incubator/blob/eaa8d436c30bed584c0be6184f82f778ac36adda/imagej/imagej-ops2/src/main/java/net/imagej/ops2/map/neighborhood/DefaultMapNeighborhood.java#L115) is an anonymous object created as part of a lambda, so it would be reasonable to expect these keys to be GC'd out of the `WeakHashMap` at any point.. which maybe makes this a moot issue?

So I guess the questions are:
* Do we actually care about preserving the per-pixel history of an operation like `Map`?
* If so, is that what we're actually doing now?
* If not, should `Map` actually both recording history?

![image](https://user-images.githubusercontent.com/1123809/196792306-c1c1e422-f966-4562-8e59-8c629fe6bb28.png)

**Comment by gselzer** [comment]
It looks like a lot of this was solved via scijava/incubator#34, right @hinerm? Is there anything left to do here? E.g. how should simplification/adaptation be handled?

**Comment by gselzer** [comment]
@hinerm I'm sorry I never answered your questions:

> Do we actually care about preserving the per-pixel history of an operation like Map?

I'm not sure that I really care - what I care about is that the return from `history.executionsUpon(output)` returns *only* the parent Op (i.e. not the dependencies). I feel like, in the case of `Map`, if `history.executionsUpon(output.firstElement())` returns the dependency, that would be optimal. The histogram-like effect you're seeing in that image, though, means we can't obtain that behavior, which is unfortunate.

> If so, is that what we're actually doing now?

Right now, we *only* record the history of Ops that are returned by an `ops.op` call (or the OpBuilder syntax, which calls that), so internal Op calls (dependencies, simplification, adaptation) shouldn't call that. Do you remember *how* you produced the `mutationMap` above?

> If not, should Map actually both recording history?

What `Map` are we talking about? If it is the `map.neighborhood` Ops you altered in scijava/incubator#64, I'm hoping to get rid of those with scijava/incubator#33.
