### ISSUE TITLE
OpHints configuration problems/limitations

### ISSUE THREAD

**Issue by hinerm** [scijava/scijava#101]
In https://github.com/scijava/incubator/commit/ca94db4d912708e99d9b6206687c1b1f993588af I skip logging outputs if the corresponding metadata flag is set. This seems like sensible behavior to me.

However, in doing so, the [ProvenanceTest#testMappingProvenance](https://github.com/scijava/incubator/blob/eaa8d436c30bed584c0be6184f82f778ac36adda/scijava/scijava-ops-engine/src/test/java/org/scijava/ops/engine/impl/ProvenanceTest.java#L155-L167) test now fails.

This route does not actually hit [my code changes](https://github.com/scijava/incubator/commit/a5b60345841ed8fb78b87c240c55d48e13740b80) on that branch. Rather, the failure is because in [DefaultOpEnvironment#resolveOpDependencies](https://github.com/scijava/incubator/blob/eaa8d436c30bed584c0be6184f82f778ac36adda/scijava/scijava-ops-engine/src/main/java/org/scijava/ops/engine/DefaultOpEnvironment.java#L553-L554) we are always creating a new set of `Hints` that disable recording - and that flag is now being *respected*.

 This seems highly dangerous to me, in part because there was no way for me to tell Ops to "yes, actually record all history during this execution" - because first of all there is no way to "invert" a hint (`Hints.minus(History.SKIP_RECORDING)` does nothing if recording hasn't already been disabled) and second the `DefaultOpEnvironment` doesn't check to see if it's overwriting previous settings.

Removing the setting of `History.SKIP_RECORDING` in `DefualtOpEnvironment#resolveOpDependencies` makes all tests pass so I'm not sure why it was being done in the first place?

**Comment by ctrueden** [comment]
See also scijava/incubator#37.

**Comment by gselzer** [comment]
> * Make Hinits mutable. This is a big change and fundamentally alters the idea of Hints being set for a particular Op match/run.

They were mutable at some point, but @ctrueden and I decided against that (can't remember the reasoning why, but we did it in scijava/incubator#46). I agree that making this change back to mutability would be tricky, and am not a fan.

> * I think maybe what we want is for the `Map` op to have some say on how its delegate op is matched, with the `skipRecording` hint flagged there, so the op [here](https://github.com/scijava/incubator/blob/3d264397f8b9841335df3084f7a9a2ea9fefa964/imagej/imagej-ops2/src/main/java/net/imagej/ops2/map/neighborhood/DefaultMapNeighborhood.java#L116) has recording disabled.. but at the time of `compute` it's too late right? It needs to be done at the matching stage somehow?

Yeah, I always wanted some extensible way for an `OpDependency` to be able to declare `Hints` for matching time, but it's tricky with the restrictions on annotation fields.

Right now, [`OpDependency.adaptable()`](https://github.com/scijava/incubator/blob/3d264397f8b9841335df3084f7a9a2ea9fefa964/scijava/scijava-ops-spi/src/main/java/org/scijava/ops/spi/OpDependency.java#L17) exists so the `adapt` Ops can prevent adapting recursion. It'd be cool if we could generalize that to some `Hints` field. The best idea off the top of my head is adding some `hints` field that is a serialized `Hints` object...

**Comment by gselzer** [comment]
@hinerm is this still an issue? Looks like scijava/incubator#64 got merged...
