### ISSUE TITLE
Ops unit tests are too slow

### ISSUE THREAD

**Issue by hinerm** [scijava/scijava#102]
Here's the current summary of unit test times on my Windows desktop:
![image](https://user-images.githubusercontent.com/1123809/199082829-089f28f0-9ea9-4b57-8eab-ef2afcd7c6c4.png)

The fact that the whole reactor takes 6 minutes is prohibitive for development.

I am in favor of having a single Ops environment that gets reused across tests, at least for default builds. For CI we could have full encapsulation and rebuild the environment each time.

**Comment by ctrueden** [comment]
I agree and have been meaning to file an issue about this, thanks. We should reuse the same environment, yeah. Also on CI, because I think slow CI is also a hindrance.

**Comment by ctrueden** [comment]
@hinerm's PR scijava/incubator#65 improves matters. Still room for further optimization, but imagej-ops2 has a lot of tests, some of which are computationally intensive, so there will be limits to how lightning-quick we can make it. @hinerm Are you OK closing this issue now, or do you want to leave it open till we have time to do another optimization pass?

**Comment by hinerm** [comment]
@ctrueden let's do a run of profiling the tests and then if that doesn't turn up anything obvious we can close this issue!

**Comment by hinerm** [comment]
So I'm still getting familiar with analyzing JFR output but have been looking at a capture of the `LilCQTest`

I looked at the Hot Spots in the Sampler tab > CPU and it says 1.2s were spent creating `java.lang.Error`. If you right-click on an entry in Hot Spots and go to "Find in Forward Calls" it will highlight one execution path to that item. You can continue to click and "Find in Forward Calls" to cycle through use-cases. (You can also do this with Reverse Calls but I find Forward a little easier to mentally parse).

Some items I've found:

338ms in `net.imagej.ops.ops2.Creators.<init>`
![image](https://user-images.githubusercontent.com/1123809/200926776-9b6ce4bd-f419-4941-a2dd-e86f82138af8.png)

468ms creating synthesized parameters
![image](https://user-images.githubusercontent.com/1123809/200927530-2fadb6fe-3f8e-4467-92ee-f932d03f1a16.png)

240ms getting therapi javadoc
![image](https://user-images.githubusercontent.com/1123809/200927722-4df3da8b-aba5-4dab-ac43-5348abc1ca65.png)

A total of ~1.5s checking `File.exists()` in SCIFIO when opening the different images for this test
![image](https://user-images.githubusercontent.com/1123809/200928131-cd662bc6-5a5d-4e4d-926e-6f569320c082.png)

A significant amount of time doing disk IO with therapi:
![image](https://user-images.githubusercontent.com/1123809/200928661-3f7a14b0-2224-4348-8aea-d1c030171a05.png)

I also noticed we are creating a SJ1 context?
![image](https://user-images.githubusercontent.com/1123809/200929510-1d886a77-e6ef-4314-a691-280019a295fa.png)

**Comment by ctrueden** [comment]
Thanks @hinerm for digging!

> I also noticed we are creating a SJ1 context?

SJC2, but yeah. SCIFIO is built on SciJava Common, so we're not getting away from this at a test time unless: A) we stop using SCIFIO; or B) we port SCIFIO to the incubator and change its plugin model to use JPMS instead.

**Comment by gselzer** [comment]
@hinerm @ctrueden this issue provides no concrete milestones (i.e. how fast is fast enough to consider this issue closed), I'm going to close this issue and make smaller issues for the particular issues @hinerm (and now I) am finding:

> 338ms in net.imagej.ops.ops2.Creators.<init>

I *could* not replicate this so I'm ignoring it.

> 468ms creating synthesized parameters

I *could* replicate this - see #131 

> 240ms getting therapi javadoc

I *could* replicate this, but I'm going to ignore it for now because scijava/incubator#79 will remove the therapi javadoc parsing.

> A total of ~1.5s checking File.exists() in SCIFIO when opening the different images for this test

I *could* not replicate this so I'm ignoring it.

> A significant amount of time doing disk IO with therapi:

See above with the therapi stuff.

It's probably worth running the profiler again once we get the YAML work merged, to see if that pathway exhibits the same performance issues...
