### ISSUE TITLE
Make use of ValidityProblems during Op matching

### ISSUE THREAD

**Issue by hinerm** [scijava/scijava#105]
With the merge of https://github.com/scijava/incubator/commit/2adac432f5efa9c85a0932548810121b30cf3306 we now have `@Optional` parameters. This comes with the caveat that parameters should only be declared in **one** location, i.e. *either* an op interface or method implementation, but not both.

The [optional-op-param-validation](https://github.com/scijava/incubator/tree/scijava/scijava-ops-engine/optional-op-param-validation) adds tests creating this ambiguous state.

In ops, [this state is currently detected](https://github.com/scijava/incubator/blob/2adac432f5efa9c85a0932548810121b30cf3306/scijava/scijava-ops-engine/src/main/java/org/scijava/ops/engine/struct/LazilyGeneratedMethodParameterData.java#L235-L249) and a [ValidityProblem](https://github.com/scijava/incubator/blob/main/scijava/scijava-common3/src/main/java/org/scijava/common3/validity/ValidityProblem.java) is created to record the issue.

However, the actual *call* into detecting parameter optionality is just passing [an anonymous list](https://github.com/scijava/incubator/blob/2adac432f5efa9c85a0932548810121b30cf3306/scijava/scijava-ops-engine/src/main/java/org/scijava/ops/engine/struct/LazilyGeneratedMethodParameterData.java#L116-L117) that is immediately discarded. This results in op requests failing with no information actually provided.

We should, at the least, be actually propagating `ValidityProblems` and including them in any "No candidates found" report at the end of a failed matching session.

^ this may not be necessary any more since https://github.com/scijava/incubator/pull/83

But I suggest the following:

- [ ] Clean up dead usages of `problems` lists [like this one](https://github.com/scijava/incubator/blob/28755f92eed318485df89e0b165bcc162ccfb624/scijava/scijava-ops-engine/src/main/java/org/scijava/ops/engine/reduce/ReducedOpInfo.java#L42-L44).
- [ ] Turn `ValidityProblem` to an enum and use that instead of message [string comparison](https://github.com/scijava/incubator/blob/28755f92eed318485df89e0b165bcc162ccfb624/scijava/scijava-ops-engine/src/test/java/org/scijava/ops/engine/OpMethodDependencyPositionTest.java#L109)
- [ ] Add a test for each other `ValidityProblem` type, modeled after the `OpMethodDependencyPositionTest`

**Comment by gselzer** [comment]
@hinerm `ValidityProblem`s are (currently) problems that are *inherently* wrong with an Op, such as an `OpMethod` missing the `static` keyword - Ops are not (currently) added to the op index when they have any validity problems - for those with issues, they are described [here](https://github.com/scijava/incubator/blob/f1fa47898653d204c34264620b40618700ca9749/scijava/scijava-ops-engine/src/main/java/org/scijava/ops/engine/DefaultOpEnvironment.java#L727) as a logging message - in that way, they *are* propagated to the user. Would you like to be doing something more?

**Comment by hinerm** [comment]
> Ops are not (currently) added to the op index when they have any validity problems - for those with issues, they are described [here](https://github.com/scijava/incubator/blob/f1fa47898653d204c34264620b40618700ca9749/scijava/scijava-ops-engine/src/main/java/org/scijava/ops/engine/DefaultOpEnvironment.java#L727) as a logging message - in that way, they _are_ propagated to the user

@gselzer you have [code here](https://github.com/scijava/scijava/issues/105#issuecomment-1599339967) that is adding `ValidityProblem`s to a list and returning. In the two use-cases of this method that `List` is just an anonymous reference that is immediately discarded. So how are those messages ever being reported?

**Comment by gselzer** [comment]
> @gselzer you have [code here](https://github.com/scijava/incubator/blob/f1fa47898653d204c34264620b40618700ca9749/scijava/scijava-ops-engine/src/main/java/org/scijava/ops/engine/struct/LazilyGeneratedMethodParameterData.java#L244-L253) that is adding `ValidityProblem`s to a list and returning. In the two use-cases of this method that `List` is just an anonymous reference that is immediately discarded. So how are those messages ever being reported?

Ooh, yeah, that's probably an oversight. We should probably be reporting those upstream!

**Comment by hinerm** [comment]
@gselzer Not sure if this is related or needs to be its own issue: why are [invalid OpMethodInfo](https://github.com/scijava/incubator/blob/ffc89fa6990112a33ba23277984555e08c3837e7/scijava/scijava-ops-engine/src/main/java/org/scijava/ops/engine/matcher/impl/OpMethodInfo.java#L454) even allowed to exist?

Intercepting the exception and storing it as a field feels like temporary field code smell. An `OpMethodInfo` never _needs_ that field itself. Would we ever actually want to keep around a collection of all the invalid infos?

**Comment by gselzer** [comment]
> @gselzer Not sure if this is related or needs to be its own issue: why are [invalid OpMethodInfo](https://github.com/scijava/incubator/blob/ffc89fa6990112a33ba23277984555e08c3837e7/scijava/scijava-ops-engine/src/main/java/org/scijava/ops/engine/matcher/impl/OpMethodInfo.java#L454) even allowed to exist?

@hinerm not totally sure, they've been around [for years](https://github.com/scijava/incubator/blame/main/scijava/scijava-ops-api/src/main/java/org/scijava/ops/api/OpInfo.java#L100)



> Would we ever actually want to keep around a collection of all the invalid infos?

I don't think so, and I don't think we do much with invalid `OpInfo`s - they're discarded [here](https://github.com/scijava/incubator/blob/ffc89fa6990112a33ba23277984555e08c3837e7/scijava/scijava-ops-engine/src/main/java/org/scijava/ops/engine/DefaultOpEnvironment.java#L763). The only thing that might be nice about the current setup is that once you look at the `validityException`, you know *all* of the issues with an `OpInfo`, not just the first issue that the `OpInfo` constructor found. But I don't know that it's worth it. Happy to try to remove the `ValidityException` logic from `OpInfo`s!

**Comment by hinerm** [comment]
@gselzer I updated the original post with goals for completion. Let me know if they make sense and sound reasonable to you

**Comment by gselzer** [comment]
> * Turn `ValidityProblem` to an enum and use that instead of message [string comparison](https://github.com/scijava/incubator/blob/28755f92eed318485df89e0b165bcc162ccfb624/scijava/scijava-ops-engine/src/test/java/org/scijava/ops/engine/OpMethodDependencyPositionTest.java#L109)

@hinerm I'm not a huge fan of this idea - `ValidityProblem` is part of SciJava Common3, so we'd have extensibility issues with an enum. I'd rather just create some `InvalidOpError` or something, if you want enums.
