### ISSUE TITLE
Priority not respected for reduced Ops

### ISSUE THREAD

**Issue by hinerm** [scijava/scijava#115]
When I make the `OutOfBoundsFactory` [optional](https://github.com/scijava/incubator/blob/5f8bdc0e97962730ec6d76bda4b5feefb4cbfc10/imagej/imagej-ops2/src/main/java/net/imagej/ops2/filter/gauss/Gaussians.java#L109) in [defaultGaussRAI](https://github.com/scijava/incubator/blob/5f8bdc0e97962730ec6d76bda4b5feefb4cbfc10/imagej/imagej-ops2/src/main/java/net/imagej/ops2/filter/gauss/Gaussians.java#L105) the [gaussRegressionTest](https://github.com/scijava/incubator/blob/5f8bdc0e97962730ec6d76bda4b5feefb4cbfc10/imagej/imagej-ops2/src/test/java/net/imagej/ops2/filter/gauss/GaussTest.java#L58) fails with a match failure between three options, including [defaultGaussRAISimple](https://github.com/scijava/incubator/blob/5f8bdc0e97962730ec6d76bda4b5feefb4cbfc10/imagej/imagej-ops2/src/main/java/net/imagej/ops2/filter/gauss/Gaussians.java#L140) and [defaultGaussRA](https://github.com/scijava/incubator/blob/5f8bdc0e97962730ec6d76bda4b5feefb4cbfc10/imagej/imagej-ops2/src/main/java/net/imagej/ops2/filter/gauss/Gaussians.java#L74). However this *does not* conflict without the `@Optional` parameter, because these latter two are properly differentiated by priority.

This happens even when giving `defaultGaussRAI` a [higher priority](https://github.com/scijava/incubator/blob/5f8bdc0e97962730ec6d76bda4b5feefb4cbfc10/imagej/imagej-ops2/src/main/java/net/imagej/ops2/filter/gauss/Gaussians.java#L101) than the other two.

It seems like `ReducedOpInfo` is [inheriting priority appropriately](https://github.com/scijava/incubator/blob/5f8bdc0e97962730ec6d76bda4b5feefb4cbfc10/scijava/scijava-ops-engine/src/main/java/org/scijava/ops/engine/reduce/ReducedOpInfo.java#L140-L142) so this was unexpected.

See branch [optional-priority-conflicts](https://github.com/scijava/incubator/tree/imagej/imagej-ops2/optional-priority-conflicts) for a starting point.

**Comment by gselzer** [comment]
@hinerm is it possible that you did not run the annotation processor after making your changes? I made a couple small changes, with things seeming to be working now on that branch

**Comment by hinerm** [comment]
> is it possible that you did not run the annotation processor after making your changes?

@gselzer possibly.. that temp commit is failing with a *different* failure than I expected. In any case, your changes work and it looks like priority is used appropriately so 🤷 

Thanks for taking a look!
