### ISSUE TITLE
Add an OpBuilder path that includes all arities of input/inType

### ISSUE THREAD

**Issue by hinerm** [scijava/scijava#119]

**Comment by hinerm** [comment]
@gselzer @ctrueden OK I am sorry to bring up OpBuilder discussion again but I failed. I can't remember why I opened this issue.

Given that we have the [*ary shortcuts in OpEnvironment](https://github.com/scijava/incubator/blob/3c5f06c33f21cdca47a22b79e86b042378dafc95/scijava/scijava-ops-api/src/main/java/org/scijava/ops/api/OpEnvironment.java#L232-L442) I am not sure why we would also want more methods in the base `OpBuilder`.

What do you two think, though? Is there a good reason to have these overloaded methods? I guess it would make code editing when changing the arity of the function? Does that feel necessary to either of you? Is there another benefit I'm overlooking?

**Comment by ctrueden** [comment]
In my view, the only urgent question here is: what, if any, of the currently public API might we regret needing to maintain for the long-term? For example, the original OpBuilder concerns that @hinerm raised and fixed were about there being a multiplicative explosion of method signatures at a single level of the builder, making it hard to navigate, but I believe that is now fixed, right? So the current set of signatures seems likely to be useful, friendly, and maintainable, right? And we don't see any obviously superior-in-all-respects way to adjust them?

If so, then my vote right now is to stick with what we have, close this, and only iterate on the builder in future based on feedback from other devs. We will be getting more feedback in October hopefully at the Brno hackathon, and of course after we release the libraries more into the wild with Fiji. There may be ideas that we are missing, or pain points that others have that we haven't had, which arise, and we can discuss how to fix at that time. But right now I doubt we have "coded ourselves into a corner" here.
