### ISSUE TITLE
Desirable Ops conveniences

### ISSUE THREAD

**Issue by hinerm** [scijava/scijava#120]
- [ ] `Shapes` specifiable with a single number
- [ ] Not needing to provide an [ExecutorService](https://github.com/scijava/incubator/blob/6dc6a92a479edffff1a0544768d41d78c4ef89cd/imagej/imagej-ops2/src/main/java/net/imagej/ops2/filter/gauss/Gaussians.java#L74-L80)

Once I got to the `ExecutorService` I realized that ImageJ Ops2 probably needs a pass updating which Ops its wrapping. And actually many of those will probably just be cut by directly wrapping [imglib2-algorithms](https://github.com/scijava/scijava/issues/56). For example, the `filter.gauss` method in the above case is now deprecated and superced by [this method](https://github.com/imglib/imglib2-algorithm/blob/d36c5204ad982bdbe687dea3c62790ddb7e71a98/src/main/java/net/imglib2/algorithm/gauss3/Gauss3.java#L136).

**Comment by gselzer** [comment]
> * [ ]  `Shapes` specifiable with a single number

@hinerm how do you propose handling conflicts? E.g. both `HyperSphereShape` and `DiamondShape` take a single number - do we prioritize one? 

> * [ ] Not needing to provide an [ExecutorService](https://github.com/scijava/incubator/blob/6dc6a92a479edffff1a0544768d41d78c4ef89cd/imagej/imagej-ops2/src/main/java/net/imagej/ops2/filter/gauss/Gaussians.java#L74-L80)

We could simply make it optional, but I'm not sure what the reasonable default would be

**Comment by gselzer** [comment]
> For the `ExecutorService`, I thought we were going to use the scijava-concurrent design (derived from ImgLib2's multithreading design) instead in future? Can we also configure a shared executor service in this quasi-static way, so it becomes part of the environment state, rather than specific to every op execution?

Yeah, this is a good idea.

> For shapes, could we support a string shorthand, like "rect-1" versus "sphere-3"? And define a converter for string → `Shape`, so that the matcher can do its magic with it?

This may very well be the only way to simplify `Shape`s  in an extensible way, but is this really any better than just using the Classes directly? You'd still have to parse imglib2-algorithm to know what shapes exist, leave yourself open to typos, etc. I'm not sure I feel strongly, but I think it's worth discussing

**Comment by hinerm** [comment]
> This may very well be the only way to simplify `Shape`s in an extensible way, but is this really any better than just using the Classes directly?

It's definitely better but doesn't meet the goal of simplified use.

Maybe this is the wrong level to be worrying about conveniences.. what really matters is that when an end user comes in to run, e.g. Mean filter, they just need to give it their image and a sigma. The logic to translate a radius to a shape doesn't necessarily have to be at the lowest level of the framework.

From what I know of the codebase, in general `Rectangle` seems like a reasonable default shape in many cases. If it was needed we could make a mechanism for Ops to suggest their own preferred defaults, similar to `optional` params.

**Comment by ctrueden** [comment]
@hinerm For the shapes issue, if you want to support a sigma for a particular operation, why not define another op lambda with `int` instead of `Shape`, which just delegates to the other one with `RectangleShape`? My intuition is that converting `int` to `Shape` always as `RectangleShape` at the converter layer would be too big of an assumption. But maybe taking an inventory of the various ops where `Shape` is used, and checking case by case for what's reasonable, would be a good next step before deciding?

**Comment by gselzer** [comment]
I'm going to say that this issue will be closed by scijava/incubator#33 , which removes the need to pass `ExecutorService`s all over.

>  Shapes specifiable with a single number

I'm going to treat this as "not planned" - @hinerm if you really want this, I suggest we create a new issue to add new Ops.
