### ISSUE TITLE
Standardize utility class pattern

### ISSUE THREAD

**Issue by gselzer** [scijava/scijava#127]
In [this review comment](https://github.com/scijava/incubator/pull/46#discussion_r761413322) @ctrueden suggested we standardize the way we create utility classes. I'm not quite sure what he would like to standardize, but I'm going to create this issue so his desire for standardization is not lost!

**Comment by ctrueden** [comment]
I use a line comment inside the private constructor with a particular string, rather than a javadoc comment.

We could also use this issue an opportunity to decide whether we are using plural (e.g. `Types`) or some suffix (e.g. `OpUtils`). We should not do both.

**Comment by gselzer** [comment]
Three things needed to fix this issue:
* Private constructor with comment explaining that it is a utility class
* Ensure standard utility class naming, preferably calling them `Foos`, `Bars`, etc.
* Make all utility classes `final`

The final thing is to get rid of the double `Ops`  utility classes.
