### ISSUE TITLE
ReducedOpInfos need better descriptions

### ISSUE THREAD

**Issue by gselzer** [scijava/scijava#129]
When you call `ops.descriptions(...)`, any `ReducedOpInfo`s get printed out as, e.g. `org.scijava.ops.engine.reduce.ReducedOpInfo@9d4ecf9` - we can do much better than that. Preferably we'd see the original `OpInfo`, with the Optional parameters removed!

**Comment by ctrueden** [comment]
If you get rid of the FQCN + method name, as I suggested in https://github.com/scijava/scijava/issues/130#issuecomment-1660747673, then it might simplify solving this issue, no? Just implement a `toString()` or whatnot for the `ReducedOpInfo`, which prints its parameters only (i.e. optional params removed)?
