### ISSUE TITLE
OpMethod descriptions should omit method parameters

### ISSUE THREAD

**Issue by gselzer** [scijava/scijava#130]
By typing `ops.descriptions("filter.gauss")` I get the following `OpMethodInfo` description:

```
net.imagej.ops2.filter.gauss.Gaussians.defaultGaussRAI(net.imglib2.RandomAccessibleInterval<T>,java.util.concurrent.ExecutorService,double[],net.imglib2.outofbounds.OutOfBoundsFactory<T, net.imglib2.RandomAccessibleInterval<T>>,net.imglib2.RandomAccessibleInterval<T>)(
	 Inputs:
		net.imglib2.RandomAccessibleInterval<T> input1
		java.util.concurrent.ExecutorService input2
		double[] input3
		net.imglib2.outofbounds.OutOfBoundsFactory<T, net.imglib2.RandomAccessibleInterval<T>> input4?
	 Containers (I/O):
		net.imglib2.RandomAccessibleInterval<T> container1
)
```

I think that the parameters of the method severely impact readability, and are redundant with respect to the parameters. I understand that the parameters are vital for uniquely identifying the method, but the point of the description is to help the user understand the Op, and the parameters (on the method, anyways) don't aid in that.

**Comment by ctrueden** [comment]
Should we even bother giving the fully qualified class + method *name*? Why not just the op name, with parameter types? That would be more succinct. As a developer, it is sometimes helpful to know where the implementation lives exactly—i.e. uniquely identify it as you say—but for user help, not necessary.

**Comment by gselzer** [comment]
> Why not just the op name, with parameter types? That would be more succinct.

That might not be a bad idea.



> As a developer, it is sometimes helpful to know where the implementation lives exactly—i.e. uniquely identify it as you say—but for user help, not necessary.

I'd think we should push developers to instead be looking at `ops.infos()`, where you'd get more relevant information.

**Comment by gselzer** [comment]
> > Why not just the op name, with parameter types? That would be more succinct.
> 
> That might not be a bad idea.

Okay, so the reason why this is tricky is because ops can have multiple names. What I'm thinking is that we could maybe try to promote the idea of "primary name" and "aliases", which could be easier to reflect in the description. Thoughts?

**Comment by hinerm** [comment]
@gselzer is it actually a problem for an op to be listed multiple times by its different names?
