### ISSUE TITLE
Dive into the performance impacts of LazilyGeneratedMethodParameterData

### ISSUE THREAD

**Issue by gselzer** [scijava/scijava#131]
Running `LiICQTest` using the Java Flight Recorder (JFR), I found that the test spent 10% of its time in `LazilyGeneratedMethodParameterData`:

![image](https://github.com/scijava/scijava/assets/29754838/4a6facac-f286-4950-839d-994cbd3fd7d4)

This aligns with what @hinerm found in #102, and so we should figure out why we're spending so long in here (specifically in `LazilyGeneratedMethodParameterData.addSynthesizedMethodParamInfo()`)

It's also possible that once we switch from Therapi to YAML (in scijava/incubator#79), this time will decrease

**Comment by ctrueden** [comment]
This issue is really about removing `LazilyGeneratedMethodParameterData` completely, now that the descriptions are part of the YAML metadata, which is quickly ingested.
