### ISSUE TITLE
Rewrite Java installation docs when Fiji ships Java 11

### ISSUE THREAD

**Issue by elevans** [scijava/scijava#147]
Whats the best/recommended way to install Java for SciJava Ops? Should I set up Java system wide or can I get away with using a `conda`/`mamba` environment?

The `InstallingSciJavaOpsInFiji.md` document suggests run `update-java-alternatives` in bash, but this wont work for Windows and MacOS users. We should update the docs accordingly.

**Comment by ctrueden** [comment]
I would suggest not to spend too much time worrying about Java installation in the immediate future. Fiji will soon ship with a newer version of Java, which will obviate the need for detailed installation instructions.

**Comment by gselzer** [comment]
Thanks for responding @ctrueden.

If anything, I think this issue should be turned into "remove the crazy Java 11 installation docs when Fiji eventually ships Java 11"
