### ISSUE TITLE
Duplicate arity documentation

### ISSUE THREAD

**Issue by hinerm** [scijava/scijava#150]
Just noticed [this section](https://github.com/scijava/incubator/blame/54b8af3021886df2530a3d9b6dd861c879ba7a2f/imagej/imagej-ops2-tutorial/docs/CallingOps.md#L57-L81) was duplicated. @gselzer was it copied because you were you going to write a second section here or should one just be deleted?

**Comment by gselzer** [comment]
I think we were talking about adding some Nil documentation there, but we did that elsewhere? Or maybe we should still do it in this document?

Regardless, I think one of the two needs to be deleted 😅

**Comment by gselzer** [comment]
I musta gotten rid of this somewhere when I ported it to RTD!
