### ISSUE TITLE
Ensure ImageJ-ops tests are testing correct Ops

### ISSUE THREAD

**Issue by hinerm** [scijava/scijava#152]
When defining test Ops we should do one or both of:

a) ensure that the same names aren't reused across multiple paradigms (e.g. `test.liftImg` in both `LiftFunctionsToRAITest` and `LiftComputersToRAITest`)
b) Use a controlled op environment, particularly one that doesn't mix in other test ops

Otherwise it is possible some tests will pass despite not testing what they are intended, e.g. due to adaptation

**Comment by ctrueden** [comment]
We could even go so far as to enforce that no two ops called `test.foo` exist, when the namespace/prefix is `test.`. That would prevent us from ever accidentally introducing a test with an overlapping op.

**Comment by hinerm** [comment]
>We could even go so far as to enforce that no two ops called test.foo exist, when the namespace/prefix is test.

It's true but the same op name within a given test file is fine, and potentially necessary if testing differentiation between two signatures.

In any case, I checked the current test ops and they're fine.
