### ISSUE TITLE
No warning when using the wrong character for declaring op names

### ISSUE THREAD

**Issue by hinerm** [scijava/scijava#156]
When mistakenly using the \` character instead of \' to declare op names, I didn't receive any kind of warning that my op was not being indexed. It would be nice to know if an op exists but is essentially unreachable due to not having an op name.

![image](https://github.com/scijava/scijava/assets/1123809/7527d228-8987-4656-858e-0ac9e88fdfa9)

**Comment by gselzer** [comment]
Another option is to make that *just work* - we'd probably just have to edit the regex (I think it's [here](https://github.com/scijava/incubator/blob/f4ce2135f01e2850f884b551de5035fef5f9dc8c/scijava/scijava-ops-indexer/src/main/java/org/scijava/ops/indexer/OpImplData.java#L160))f

**Comment by hinerm** [comment]
> Another option is to make that _just work_ - we'd probably just have to edit the regex (I think it's [here](https://github.com/scijava/incubator/blob/f4ce2135f01e2850f884b551de5035fef5f9dc8c/scijava/scijava-ops-indexer/src/main/java/org/scijava/ops/indexer/OpImplData.java#L160))

I like this idea.. whenever you get to work on this, double-check what happens if you do `names=` with no value?

**Comment by hinerm** [comment]
> Another option is to make that _just work_ - we'd probably just have to edit the regex (I think it's [here](https://github.com/scijava/incubator/blob/f4ce2135f01e2850f884b551de5035fef5f9dc8c/scijava/scijava-ops-indexer/src/main/java/org/scijava/ops/indexer/OpImplData.java#L160))

@gselzer I don't see any actual uses of the indexer:
![image](https://github.com/scijava/scijava/assets/1123809/471db92c-2699-4641-a53e-462977d37af3)

How is it being used..?

**Comment by ctrueden** [comment]
Ahh, this reminds me: we were originally going to have scijava-ops-indexer its own repository and separately published project, so that the multi-module Maven project using it at build time would not have this "non-Maven-way" code smell.

But if scijava-indexer is going to depend on scijava-ops-api now, we would also need scijava-ops-api and all its dependencies to be a separate repo as well? Tricky.....
