### ISSUE TITLE
Migrate to ReadTheDocs

### ISSUE THREAD

**Issue by hinerm** [scijava/scijava#159]
Per team discussion today we agreed that we'll make a ReadTheDocs page for our documentation.

This will be our first Java-based RTD page, but we can look at other projects like [QuPath](https://qupath.readthedocs.io/en/0.4/)

**Comment by hinerm** [comment]
Target source code location: `doc/ops` in incubator basedir

Hosted on `ops.scijava.org`

**Comment by ctrueden** [comment]
The `ops.scijava.org` subdomain is now a CNAME to `readthedocs.io`, so it should "just work" once the RTD site is pushed.
