### ISSUE TITLE
OpRegressionTest fails in intellij but passes on command line

### ISSUE THREAD

**Issue by hinerm** [scijava/scijava#160]
On [main](https://github.com/scijava/incubator/commits/main), when I run the [OpRegressionTest](https://github.com/scijava/incubator/blob/0cada57986d7b15c513f8fab3fbc1469a440cdd8/imagej/imagej-ops2/src/test/java/net/imagej/ops2/OpRegressionTest.java#L41-L45) from IntelliJ it only finds 1840 ops.

When I run it on the command line this test passes (1841).

The op that is missing is [`org.scijava.ops.engine.eval.DefaultEval`](https://github.com/scijava/incubator/blob/0cada57986d7b15c513f8fab3fbc1469a440cdd8/scijava/scijava-ops-engine/src/main/java/org/scijava/ops/engine/eval/DefaultEval.java#L50)

**Comment by ctrueden** [comment]
Is it due to missing JavaScript Nashorn engine when running with Java >14?

**Comment by hinerm** [comment]
> Is it due to missing JavaScript Nashorn engine when running with Java >14?

I don't think so.. I'm running Java 11 in both environments
