### ISSUE TITLE
Remove nulls in op descriptions

### ISSUE THREAD

**Issue by hinerm** [scijava/scijava#169]
As [seen here](https://github.com/scijava/scijava/issues/167#issue-2040202037), parameters in `ops.help` output have `null` values. Presumably this should be the parameter name, or something generic ("in1", "in2"), or just absent.

This may have been fixed in https://github.com/scijava/incubator/pull/101 and needs to be tested

**Comment by gselzer** [comment]
> This may have been fixed in [scijava/incubator#101](https://github.com/scijava/incubator/pull/101) and needs to be tested

It has not been fixed :frowning:

I'm on it!
