### ISSUE TITLE
Prune obsolete modules

### ISSUE THREAD

**Issue by ctrueden** [scijava/scijava#172]
There are some modules that appear unused now throughout the codebase, and could be removed:

* scijava-parse2
* scijava-testutil
* imagej-testutil

In addition, imagej-mesh2 has been replaced by imglib2-mesh (see #171), so imagej-mesh2 should also be removed once its usage has been purged.

There are a couple of other modules that nothing `requires`, but we want to keep because they are testing things: `scijava-discover-test`, `scijava-ops-benchmarks`, `imagej-ops2-tutorial`. And a couple of modules that are depended on via other mechanisms: `scijava-indexer` and `scijava-taglets`.

And `scijava-persist` is not related to scijava-ops, so will remain in the incubator after Ops moves out. :house:

**Comment by gselzer** [comment]
This was completed in scijava/incubator#109
