### ISSUE TITLE
Building a fully-discovered OpEnvironment is broken from Python

### ISSUE THREAD

**Issue by gselzer** [scijava/scijava#175]
Running the notebook in the tutorials currently breaks, because it calls [this method](https://github.com/scijava/incubator/blob/e40236ea5fe6e9b48b5ea2d559491a1a20ec4541/scijava/scijava-ops-api/src/main/java/org/scijava/ops/api/OpEnvironment.java#L81) with an empty array when we meant for it to call [this method](https://github.com/scijava/incubator/blob/e40236ea5fe6e9b48b5ea2d559491a1a20ec4541/scijava/scijava-ops-api/src/main/java/org/scijava/ops/api/OpEnvironment.java#L75). Since these methods have a lot of overlap, I'm thinking we should probably rename them.

I'm tentatively thinking the following: 
* `OpEnvironment.getBareEnvironment()` -> `OpEnvironment.buildEmpty()`
* `OpEnvironment.getEnvironment()` -> `OpEnvironment.build()` (I think the majority of people will use this one, so I like the above being modified to get 
* `OpEnvironment.getEnvironment()` -> delete (this functionality is the same as `getBareEnvironment()` + `OpEnvironment.discoverUsing()`

I also thought it'd be nice to get the name a lot shorter, but I can't think of anything better. My second choice would be `OpEnvironment.get()`, although I like `build()` better because it aligns better with how we create a new `OpEnvironment` from every call.

**Comment by hinerm** [comment]
@gselzer 

>Since these methods have a lot of overlap, I'm thinking we should probably rename them.

I don't think there's any need for two methods here. Just have a single `static OpEnvironment getEnvironment(Discoverer... discoverers)` since varargs allows for no params. Then do a check, if `discoverers` is `null` or empty, use `ops.discoverEverything();`

**Comment by gselzer** [comment]
> @gselzer
> 
> > Since these methods have a lot of overlap, I'm thinking we should probably rename them.
> 
> I don't think there's any need for two methods here. Just have a single `static OpEnvironment getEnvironment(Discoverer... discoverers)` since varargs allows for no params. Then do a check, if `discoverers` is `null` or empty, use `ops.discoverEverything();`

@hinerm what would you prefer in the case where the user wants an empty environment?

**Comment by hinerm** [comment]
> what would you prefer in the case where the user wants an empty environment?

The existing [getBareEnvironment](https://github.com/scijava/incubator/blob/e40236ea5fe6e9b48b5ea2d559491a1a20ec4541/scijava/scijava-ops-api/src/main/java/org/scijava/ops/api/OpEnvironment.java#L66-L73) is fine

**Comment by hinerm** [comment]
OK, we were basically saying the same thing. I think the plan you outlined sounds great!
