### ISSUE TITLE
Potential paper use cases

### ISSUE THREAD

**Issue by hinerm** [scijava/scijava#182]
Currently considering the following use cases for SJ Ops for the first paper (3 minimum required):

1. Recreating an analysis using OpenCV - e.g. segmentation/tracking (requires https://github.com/scijava/scijava/issues/158)
2. Translating [FlimJ-ops](https://github.com/flimlib/flimj-ops) to SJ Ops
3. Lazy, scalable ops (@axtimwalde)
4. Repeating @elevans published IJ ops work

For reference on how to do the use cases:
https://www.frontiersin.org/articles/10.3389/fcomp.2020.00008/full#h4

**Comment by elevans** [comment]
I have a repo where I keep and share my ImageJ/Fiji scripts [here](https://github.com/elevans/fiji-scripts). I have a branch there, `scijava-ops` that has SciJava Ops versions of my Fiji scripts.

**Comment by elevans** [comment]
I just created a [new branch](https://github.com/scijava/incubator/tree/scijava-ops-docs/add-examples) in the incubator where I added a new section, **Examples**, to the SciJava Ops read the docs. It uses sphinx-tabs to display tabbed code blocks (do `pip install sphinx-tabs`). The current example does a Gaussian blur subtraction in Python/Jython and Groovy. My vision is to add more here of course, like Java etc...

**Comment by hinerm** [comment]
Working on the OpenCV use case, this is some code I adapted from [this guide](https://docs.opencv.org/4.x/d2/d0a/tutorial_introduction_to_tracker.html) to do tracking with the Java API (using a manual starting point for [this sample data](https://github.com/opencv/opencv_extra/tree/master/testdata/cv/tracking)):
```java
Mat m = imread("/Users/hiner/Downloads/00000001.jpg");
Tracker tracker = TrackerCSRT.create();
Rect roi = new Rect(310, 130, 100, 100);
tracker.init(m, roi);
rectangle(m, roi, new Scalar(255), 2, 8, 0);
imwrite("/Users/hiner/temp/" + 1 + ".png", m);
for (int i=2; i<7; i++) {
	m = imread("/Users/hiner/Downloads/0000000" + i + ".jpg");
	tracker.update(m, roi);
	rectangle(m, roi, new Scalar(255), 2, 8, 0);
	imwrite("/Users/hiner/temp/" + i + ".png", m);
}
```

It works! But I don't really see how to adapt this to Ops since object tracking is a stateful thing. I think we would need to write custom Ops on top that do some variation of taking input roi(s), the desired tracking algorithm, and data set, and possibly return a map of images to rois (or something like that) representing the completed track.

I'm going to move on to just try segmentation.
