### ISSUE TITLE
Discuss Op versioning

### ISSUE THREAD

**Issue by hinerm** [scijava/scijava#185]
Per @gselzer: 
>We should probably have documentation somewhere on how versioning should work for Ops.

**Comment by ctrueden** [comment]
"Reasoning about Ops" page on ops.scijava.org, with sections:

- Intro to Op introspection
  - OpInfo objects
  - "Rich" ops vs "bare" ops with only functional type not metadata
- Op signatures
  - `Ops.signature` method
  - `env.opFromSignature` to reconstruct -- including current caveats (links to open issues #219, #220)
- Versions
  - framed as "part of the signature" maybe?
- InfoTrees
  - walking dependencies
  - does *not* cover reduction, adaptation, etc., which are considered implementation details
- Op history
  - including how to pass hints to control this

**Comment by elevans** [comment]
@elevans needs to create a new section in the docs for Op versioning and the outlined subtopics.
