### ISSUE TITLE
ops.help in matching failure can cause infinite loop

### ISSUE THREAD

**Issue by hinerm** [scijava/scijava#187]
[This call](https://github.com/scijava/incubator/blob/f78a0d83ff060316e70e7f92685b4f58186bfb09/scijava-ops-engine/src/main/java/org/scijava/ops/engine/matcher/impl/DefaultOpMatcher.java#L83) to `env.help` will trigger another match, which if itself is invalid will cause an infinite loop and lead to `StackOverflowException`.

Observed on [opencv-ops](https://github.com/scijava/incubator/tree/opencv-ops) in [this commit](https://github.com/scijava/incubator/commit/aa2765019142c6fba1135913d30f2d0b98720884) adding new `engine.simplify` methods.

I think this will only happen if the invalid Op is an `engine.simplify` Op

**Comment by hinerm** [comment]
In this particular case, separating the ops arbitrarily by priority avoided the infinite loop

**Comment by gselzer** [comment]
I think that the best idea here would be to change that call to run `env.helpVerbose()`, which does not attempt to simplify (in the current design). I think it has the added benefit of jumping straight to the verbose information, which the user probably wants anyways if matching didn't work, but I'd defer to @elevans' opinion on that one.

**Comment by elevans** [comment]
I just talked to @gselzer about this and I agree that using `env.helpVerbose()` here instead of `env.help()` 1) results in an ideal output for this scenario and 2) allows us to bypass this for now.

**Comment by gselzer** [comment]
Fixed with scijava/incubator#129
