### ISSUE TITLE
Add API to access available Hints

### ISSUE THREAD

**Issue by gselzer** [scijava/scijava#190]
It would be slick to add additional API to discover the available hints, much like have the `OpEnvironment.help()` API to discover the available Ops. I'm foreseeing something like:
```
Hints.describeAll();
--- OUTPUT ---
Available Hints:
  Adaptation:
    - FORBIDDEN: Disables Op adaptation
  Progress:
    - TRACK: Enables logging progress updates
``` 
Of course, this relies on a way of making hints discoverable, which likely means that the `BaseOpHints` classes need to be discoverable. We then have an interesting question of how the `Hints` are described in Ops - we currently use strings, but there is an interesting alternative in `Class`es:

```java
public interface Hint {
	default String prefix() {
		return this.getClass().getSimpleName();
	}

	Class<? extends HintType>[] types();
}

// NB: Marker Interface
public interface HintType {
}
```

We could then have implementations including:
```java
	public static final class Simplification implements Hint {

		@Override
		public Class<? extends HintType>[] types() {
			return new Class[] { FORBIDDEN.class, IN_PROGRESS.class};
		}

		public static final class FORBIDDEN implements HintType {}
		public static final class IN_PROGRESS implements HintType {}
	
```

And then in e.g. `OpDependency` we could refactor to:
```java
/** Annotates a helper op as a field that should be auto injected. */
@Retention(RetentionPolicy.RUNTIME)
@Target({ ElementType.FIELD, ElementType.PARAMETER })
public @interface OpDependency {

	/** The name of the Op to inject. */
	String name();

	/** Set to false if the dependency should not be adapted */
	Class<? extends HintType> [] hints() default {};
}
```

Which in practice would look like:

```java

This seems like a big change, though - we could additionally make a discoverable interface that simply reports the `String` conventions...
	@OpHints(hints = { Simplification.FORBIDDEN.class })
	@OpField(names = "engine.simplify")
	public final Function<Byte, Number> byteSimplifier = b -> b;
```

**Comment by hinerm** [comment]
Per discussion, we currently envision the Hints as being largely developer-focused and accessible via documentation, relying on published javadoc and potentially code examples to keep up-to-date. It's not a primary mechanism we want people interacting with from an extensibility perspective. So for now we're closing as unplanned, but are open to revisiting in the future if a clear need is demonstrated.
