### ISSUE TITLE
Create nullary converters

### ISSUE THREAD

**Issue by hinerm** [scijava/scijava#196]
The ops in [ConvertImages](https://github.com/scijava/incubator/blob/a969114d2f047a47dffb3ca2d189a3263d56d98a/scijava-ops-image/src/main/java/org/scijava/ops/image/convert/ConvertImages.java#L74-L85) are currently written as functions that always allocate new output.

It would be nice if we had nullary options and could just write:

```
ops.nullary("convert.int8").output(img).compute();
```

to modify an existing image.

**Comment by gselzer** [comment]
@hinerm can you elaborate a bit more on what you want?

Suppose you have a `RandomAccessibleInterval<FloatType>` - can you tell me what you want to do?
* If you're looking to scale the values in your float type, you could probably do that with `convert.scale` (which we somehow do not have in SciJava Ops Image...), but you'd want an `Inplace`, not a `Computer`.
* If you're looking to obtain a reference to a `RandomAccessibleInterval<ByteType>`, you'll need to call some unary Op. The hope was that you could use `ConvertImages` if you want a `Function`, and could rely upon an adapted version of `ConvertTypes` if you want a `Computer`.

**Comment by hinerm** [comment]
>If you're looking to scale the values in your float type, you could probably do that with convert.scale (which we somehow do not have in SciJava Ops Image...), but you'd want an Inplace, not a Computer.

Yes that's fair. I'd want an `Inplace`.

>@hinerm can you elaborate a bit more on what you want?

Something that can behave like the `Image > Type` adjustments in ImageJ without duplicating data. I'm not sure this is actually possible with strong type restrictions.. maybe if you had a `RandomAccessibleInterval<RealType>` the types could be swapped? But maybe still not because of the backing array? I don't really know. But converting in place is very nice in IJ1 and having to make a copy to convert feels like a loss.

**Comment by ctrueden** [comment]
> Something that can behave like the Image > Type adjustments in ImageJ without duplicating data.

Those operations definitely duplicate the data. It's different backing primitive arrays. It just throws way the old data afterward. :laughing:

**Comment by hinerm** [comment]
>Those operations definitely duplicate the data.

In that case this is probably unnecessary
