### ISSUE TITLE
Computers with generic output parameters not callable as a Function without output type specified

### ISSUE THREAD

**Issue by gselzer** [scijava/scijava#209]
The following test fails in Op execution, due to a `ClassCastException`. The issue arises from the `Any` not respecting the bounds of the original matched Op, which requires the output be a `RealType`. Of course, the adaptor matched is a `ComputerToFunctionViaFunction`, which matches an `ArrayImg->ArrayImg` engine.create Op, which is wrong.

The solution, here, is that *at least in adaptation* Any outputs must be bounded in the dependencies by the adapted Op's types.
```java
	@Test
	public void testPercentile() {
		var p = ops.op("stats.percentile").arity2().input(randomlyFilledImg, 50d).apply();
		Assertions.assertEquals(128d, percentile.getRealDouble(), 0.00001d,
			"50-th Percentile");
	}

```

Until this is fixed, specifying the output type allows a workaround:

```java
	@Test
	public void testPercentile() {
		var p = ops.op("stats.percentile").arity2().input(randomlyFilledImg, 50d).outType(DoubleType.class).apply();
		Assertions.assertEquals(128d, percentile.getRealDouble(), 0.00001d,
			"50-th Percentile");
	}

```

**Comment by hinerm** [comment]
Personally I see this as a significant barrier to usability and something that should be top priority for fixing
