### ISSUE TITLE
Allow retrieval of values of Ops/parameters from @Plugin/@Parameter annotations

### ISSUE THREAD

**Issue by gselzer** [scijava/scijava#26]
Scijava's [Plugin annotation](https://github.com/scijava/scijava-common/blob/482c170eefe58078a1affc0e8da5665012501ac1/src/main/java/org/scijava/plugin/Plugin.java#L79) and Scijava-ops' [Parameter annotation](https://github.com/scijava/scijava-ops/blob/b7fdd065d521f6b812a5cf1e6d35ce748407572a/src/main/java/org/scijava/param/Parameter.java#L65) allow for a description, however these values are not retained within `OpClassInfo` or `OpFieldInfo` (as far as I can tell). This data can be helpful both in fixing Ops matching errors as well as being used by the Op `help` (it was used in the previous iteration of the help Op, anyways).

Questions:
* Are there any reasons not to support this?
* What other annotation data might we want to support that is not already done so?

**Comment by ctrueden** [comment]
Superseded by scijava/incubator#28.
