### ISSUE TITLE
read the docs: Paper links to examples don't work

### ISSUE THREAD

**Issue by hinerm** [scijava/scijava#276]
They go to `paper-2024/examples`

![image](https://github.com/user-attachments/assets/d9c2d173-6654-4866-8e02-a97097b1654b)

![image](https://github.com/user-attachments/assets/77833213-f70c-4caf-92a4-2739638191cb)

**Comment by gselzer** [comment]
For fixing later, the links are [here](https://ops.scijava.org/en/latest/paper-2024/index.html)
