### ISSUE TITLE
Determine a multithreading solution

### ISSUE THREAD

**Issue by gselzer** [scijava/scijava#31]
Most existing Ops rely on [`DefaultChunker`](https://github.com/imagej/imagej-ops/blob/master/src/main/java/net/imagej/ops/thread/chunker/DefaultChunker.java) when they wish to multithread a process. This process is more complicated to introduce in scijava-ops because:
1) It requires all ops that want to multithread to require an `ExecutorService` as a parameter, something that could/should be injectable by the `OpService`.
2) The tests for this `Op` introduce `junitbenchmark`; it would be nice if we did not have to introduce this.

There are a few different approaches that we can take:
1) Create some sort of static method that mimics the behavior of `Chunk`
2) Add support for what is going on in https://github.com/imglib/imglib2-algorithm/issues/81

Would it be possible to create a special mutlithreading `OpDependency` that, upon discovery, the matcher could inject its `ThreadService` into? i.e. if you had a
```
@OpDependency(name = "thread.chunker")
private NullaryComputer<Chunk> chunkerOp;
```
Ops could find a `Computer` that takes an `ExecutorService` as input and wrap that into a `NullaryComputer` by injecting its `ExecutorService`?

**Comment by gselzer** [comment]
As an aside to this issue here is a list of the ops that use `Chunk`s:

* [`HistogramOfOrientedGradients2D`](https://github.com/imagej/imagej-ops/blob/master/src/main/java/net/imagej/ops/features/hog/HistogramOfOrientedGradients2D.java)
* [`DefaultProjectParallel`](https://github.com/imagej/imagej-ops/blob/master/src/main/java/net/imagej/ops/transform/project/DefaultProjectParallel.java)

There are also numerous math and map Ops that could use this, however these are less dependent on `Chunk`

**Comment by ctrueden** [comment]
Solution to this issue will likely revolve around a new parallelization framework in development by @maarzt and @tpietzsch; see imglib/imglib2#269.

**Comment by gselzer** [comment]
So I was going to declare that this issue will be closed by scijava/incubator#13, except for the fact that the multi-threading solution proposed there *cannot actually be used within scijava-ops* (since that solution is image-specific). More thinking will be required on this 🤔

**Comment by maarzt** [comment]
Hi @gselzer, I just wanted to tell you that there two non image specific classes for parallelization in imglib2 that might come in very handy for the problem in SciJava: `Parallelization` and `TaskExecutor`. Please have a look at the javadoc:

* https://scijava.org/javadoc.scijava.org/ImgLib2/net/imglib2/parallel/Parallelization.html
* https://scijava.org/javadoc.scijava.org/ImgLib2/net/imglib2/parallel/TaskExecutor.html
* https://scijava.org/javadoc.scijava.org/ImgLib2/net/imglib2/parallel/TaskExecutors.html

Here is a tiny example that calculate the squares of the numbers 1 to 10. This can be easily done sequentially or multit-hreaded using this API. Also `TaskExecutor` is mostly just a simple to use wrapper around `ExecutorService`, there is `taskExecutor.getExecutorService()` if you need it ;)
```
import net.imglib2.parallel.Parallelization;
import net.imglib2.parallel.TaskExecutor;

import java.util.Arrays;
import java.util.List;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

public class MultiThreadingExample {

	private static List< Integer > calculateSquares(List< Integer > values) {
		TaskExecutor taskExecutor = Parallelization.getTaskExecutor();
		return taskExecutor.forEachApply(values, x -> x * x);
	}

	public static void main(String... args) {

		List< Integer > values = Arrays.asList(1, 2, 3, 4, 5, 6, 7, 8, 9, 10);

		Parallelization.runSingleThreaded( () -> {
			List< Integer > squares = calculateSquares(values);
			System.out.println("Single threaded results: " + squares);
		});

		Parallelization.runMultiThreaded( () -> {
			List< Integer > squares = calculateSquares(values);
			System.out.println("Multi threaded results: " + squares);
		});

		Parallelization.runWithNumThreads( 5, () -> {
			List< Integer > squares = calculateSquares(values);
			System.out.println("Five threads results: " + squares);
		});

		ExecutorService executorService = Executors.newCachedThreadPool();
		Parallelization.runWithExecutor(executorService, () -> {
			List< Integer > squares = calculateSquares(values);
			System.out.println("ExecutorService results: " + squares);
		});
		executorService.shutdown();

	}
}

```

**Comment by gselzer** [comment]
@maarzt cool! I remember reading about this...

I think the only issue with this is that we don't want to impose any imglib dependencies on Scijava modules (this is the reason for separation between scijava-ops and imagej-ops2). Nothing in the `net.imglib2.paralell` package seems to be dependent on images anyways; what do you think about exporting this package into a new `scijava-parallel` module? This way we could make use of `TaskExecutor` and `Parallelization` across all Scijava modules...

I have one more question: is there a reason that `TaskExecutor.forEachApply()` takes a `List` as opposed to an `Iterable`? It would be nice from a typing standpoint (and thus allow us to create broader lifting Ops).

**Comment by maarzt** [comment]
> What do you think about exporting this package into a new `scijava-parallel` module?

I think that's the way to go.

> I have one more question: is there a reason that `TaskExecutor.forEachApply()` takes a `List` as opposed to an `Iterable`? It would be nice from a typing standpoint (and thus allow us to create broader lifting Ops).

There are two reasons here:

1. The list's `size()` method is used to allocate a container with the correct capacity to hold the results. The `Iterable` interface is lacking a `size()` method, and not initializing with the correct capacity will slow down the computation a bit. 
2. Using the `List` interface means that the parameters are in a specific order. The order is kept for the results list. This allows a clear correspondence between parameters and results.

Neither of the reasons is absolute. A easy solution would be to just copy the `Iterable` into a `List`. If your `Iterable` has very many items, deviding it into chunks is anyway important for good performance.

**Comment by ctrueden** [comment]
I am enthusiastically in favor of splitting ImgLib2's parallelization framework to its own component in the SciJava layer. :+1:

I will point out that the name `scijava-parallel` is already [in use](https://github.com/fiji-hpc/scijava-parallel), so we need to name it differently. Other than that I don't have a strong preference for the name.

**Comment by gselzer** [comment]
Time commitment: 1 week.

@ctrueden who is best suited to complete this task?
