### ISSUE TITLE
Improve relative path reasoning for .list files

### ISSUE THREAD

**Issue by gselzer** [scijava/scijava#41]
Let's say that we have 3 `.list` files named `Globals.list`, `Inplaces.list`, and `InplacesToFunctions.list` (this is my use case). `Inplaces.list` uses some of the functions in `Globals.list`, and **imports it using a relative path** (in my case, both of these files are in the same package, but this doesn't really matter). 

Our third file, `InplacesToFunctions.list`, is in a different package. It wants to use some of the functions in both `Inplaces.list` and `Globals.list`; it would naturally make sense to import only `Inplaces.list` and then get all of the functions in both. However, `generate-groovy` cannot find `Globals.list`, since it takes the relative path given in `Inplaces.list` and appends it to the absolute path of `InplacesToFunctions.list`. This is wrong, and this scheme only works if all three `.list` files are in the same package.

`generate-groovy` instead needs to append the relative path given in `Inplaces.list` and append it to the absolute path of `Inplaces.list` when determining the imports for `InplacesToFunctions.java`.

**Comment by ctrueden** [comment]
Rather than supporting chained imports, I'd advise to just put everything you want to share into `Globals.list`, even if not every template uses all the functions there.

I know, it's not super modular, but this is only for our local code generation step, so it's probably fine.

**Comment by gselzer** [comment]
Hmm, I guess we could, the only issue I see with that is that there can be no method overriding, which will result in some really long and/or confusing lines in the `.vm` files. But maybe this is okay.

**Comment by gselzer** [comment]
Time commitment: 1 week
