### ISSUE TITLE
Consider Impact of Separate Data Structure used by DefaultOpEnvironment.adaptOp

### ISSUE THREAD

**Issue by gselzer** [scijava/scijava#48]
[`DefaultOpEnvironment.adaptOp()`](https://github.com/scijava/incubator/blob/0cc4c2cf5ea153d8ecc1affd0087dbacd7d3a9ae/scijava/scijava-ops/src/main/java/org/scijava/ops/impl/DefaultOpEnvironment.java#L239) obtains its set of `adapt` Ops simply by requesting *all of them* from the `opCache`. As scijava-ops builds a larger collection of `adapt` Ops, sorting through this collection to find the `adapt` Op needed becomes a bigger and bigger ask.

It might then be worthwhile to create a second data structure (most likely a `Map<Class<?>, Set<OpInfo>>`) to store all `adapt` `OpInfo`s corresponding *to a certain op type*. For example, this `Map` might contain a `Set` of all `OpInfo`s corresponding to the `adapt` Ops that can adapt to `Function`s, `Computer.Arity0`s, etc. and would thus eliminate the numerous checks against `adapt` Ops that give you `Inplace`s when you are looking for some `BiFunction`.

It is worth considering, however, how useful such an addition might be. When would we create it? It would be efficient to create such a structure during the `initOpCache` method, but does it make sense to create it there? Only if this structure is considered part of the `opCache`. Are ops adapted enough (per `OpEnvironment`) for this to make a significant increase in efficiency? @ctrueden do you have any intuition on this?

**Comment by ctrueden** [comment]
My intuition is to cache the adapt ops as they are retrieved, so that subsequent retrievals are faster, rather than pregenerating such a cache in advance.

But most important is to validate the performance. How slow is it to retrieve adapt ops? If you add this caching layer, how slow is it then? If it's way faster, we should add it. And if not, not bother. Don't prematurely optimize.

**Comment by gselzer** [comment]
> My intuition is to cache the adapt ops as they are retrieved...rather than pregenerating such a cache in advance.

Hmm, that is fair. We could generate the cache as we go, adding them as we traverse through the long list given by `infos("adapt")`. 

> How slow is it to retrieve adapt ops?

This is an interesting question. Obtaining the set of all `adapt` ops is of course constant time. The worst-case time complexity for finding a *suitable* `adapt` Op from that list is linear in terms of the set of adapt Ops (we fail fast whenever the `adapt` Op being looked at could not convert to the requested functional type).

If we were to implement such a cache, the complexity of finding a suitable `adapt` Op would still be linear but would be linear in terms of the number of `adapt` Ops *with the same raw type*. As of this writing we have well over 200 adapt Ops and maybe only 10 pertain to adapting any singular functional type. This would suggest decreasing the *worst case* number of checks by a magnitude of 10. 

So is it worth it? Probably not, since are really only going to decrease the amount of times that we are failing fast.

**Comment by gselzer** [comment]
Time commitment: 1 week

**Comment by gselzer** [comment]
Closing this issue due to the discussion above.
