### ISSUE TITLE
Add therapi to build system upstream

### ISSUE THREAD

**Issue by ctrueden** [scijava/scijava#57]
Add therapi annotation processing mechanism to pom-scijava-base for all projects, with ability to opt-out via a property (ideally).

**Comment by gselzer** [comment]
Time Commitment: 1 day

**Comment by ctrueden** [comment]
The mainline branch of pom-scijava now has therapi-runtime-javadoc infrastructure added. Just need a pom-scijava 32.0.0 release, and then incubator extending it, to finish resolving this issue.

**Comment by gselzer** [comment]
The incubator is already at pom-scijava version 34.1.0, so I think we're good to go on this!
