### ISSUE TITLE
Cleanly separate core ops infrastructure from ops discovery

### ISSUE THREAD

**Issue by ctrueden** [scijava/scijava#59]
For ops discovery, we want to use an industry standard mechanism (or mechanisms). Maybe Spring (#55), maybe plain  `ServiceLoader` via JPMS `module-info.java`, maybe even something else. The Ops design should not conflate this with the engine itself, which has only the `OpEnvironment` interface, and accessor(s) for the `OpInfo`s it has in its bag. Similarly, `OpService` as built on the SciJava service framework is a separate thing, which should not be part of the core ops engine at all.

To ensure this, the scijava-ops-api and scijava-ops-engine modules (or whatever they end up being named) _must not_ depend on scijava-indexer, scijava-plugin, scijava-context, and similar layers relating to discovery, dependency injection, or application containers. It must be possible to create a "vanilla" OpEnvironment with a explicitly specified bag of ops.

**Comment by gselzer** [comment]
Time commitment: 1 week

(NB it could take substantially longer depending on which/how many modules we want to partition, but I think this is unlikely)

**Comment by gselzer** [comment]
This has been completed. I can't determine which commit did it, but it was definitely done by the time we merged https://github.com/scijava/incubator/pull/40.

**Comment by gselzer** [comment]
While we have not yet adopted Spring, Classgraph, or any other industry-standard discovery mechanism, any/all of them should be easily integrated through the `Discoverer` abstraction.
