### ISSUE TITLE
Document Ops project goals in the new README

### ISSUE THREAD

**Issue by ctrueden** [scijava/scijava#60]
The README is very important for newcomers. We need to explain "Why Ops" there:

- unified algorithms framework
    - improves extensibility—tooling can expose all available ops in a general way—e.g. Ops Browser
    - matcher improves extensibility / flexibility / performance—algorithms can be overridden to perform better or in more cases
- needs to be as easy as possible to contribute / adapt algorithms into the framework
- algorithms expressed in this structure need to conform to the expectations—e.g. computer

And have some very succinct illustrations in code for both _consuming_ ops, and _implementing_ new ops.

**Comment by gselzer** [comment]
Time Commitment: 1 week (let's make this thorough!)
