### ISSUE TITLE
Split scijava-ops into more core modules

### ISSUE THREAD

**Issue by ctrueden** [scijava/scijava#61]
Components scijava-ops needs to be split into:
- scijava-struct / scijava-param
- scijava-types—generic type matching utils
    - org.scijava.types.Types static utility class
    - org.scijava.types.Nil—build on Guava TypeToken
- scijava-ops (or scijava-ops-engine?)—matcher
- scijava-ops-api—lightweight, no deps, for the annotation ifaces
- SJC3 stuff:
    - scijava-context
    - scijava-plugin?
    - others
- scijava-function
    - move org.scijava.ops.function package out of "ops" umbrella

**Comment by gselzer** [comment]
Closely related to #59 

Time commitment: 1-2 weeks

**Comment by gselzer** [comment]
SciJava Ops itself has been split up into clean, unifunctional modules. See scijava/incubator#31, scijava/incubator#29, other PRs.
