### ISSUE TITLE
Enforce better package relationships at build time

### ISSUE THREAD

**Issue by ctrueden** [scijava/scijava#62]
__No circular dependence between packages.__ E.g. if `org.scijava.ops.a` imports something from `org.scijava.ops.b`, then `org.scijava.ops.b` must not also import something from `org.scijava.ops.a`—_including subpackages_.

__No dependence on subpackages.__ E.g. Classes of `org.scijava.ops` must not import classes from `org.scijava.ops.a`, `org.scijava.ops.a.b`, etc.

To facilitate this, we should employ a dependency analysis step during the build, and fail if these rules are broken. We could use [JDeps](https://docs.oracle.com/en/java/javase/11/tools/jdeps.html) and/or [JDepend](https://github.com/clarkware/jdepend) (see also [jdepend-maven-plugin](https://github.com/mojohaus/jdepend-maven-plugin)).

**Comment by gselzer** [comment]
Somewhat related to #59, #61

Time commitment: 2 weeks
