### ISSUE TITLE
Improve the shortcomings of therapi javadoc processing

### ISSUE THREAD

**Issue by gselzer** [scijava/scijava#65]
There are a couple reasons to move on from/fork therapi, discussed in (and then copied here from) https://github.com/scijava/incubator/pull/28:

1. Therapi is an source-time annotation processor. It might have access to the parameter names of methods, even though they are typically not stored into the bytecode. If so, we could map the @param names to the actual parameter names, in case the @param declarations are out of order, or some are missing, or some are spurious. This would be better than the current assumption that everything is there, and in same order as the method.
2. In the case of mixed @param and @input/@output, therapi indexes things in such a way that the order is lost. We should consider either:
* Submitting an issue and/or PR to therapi adding a general-purpose getter of all the javadoc annotations in original order; or
* Fork therapi and merge its logic into scijava-indexer, so that everyone can have this functionality without incurring additional annotation-time dependencies.

**Comment by gselzer** [comment]
The conversation in https://github.com/scijava/incubator/pull/28#discussion_r694164841 yields another objective: If we improve therapi, we should retain the method parameter names. This would allow Op authors to explain some (but not all) of their parameters (for example, they could avoid describing those that whose purpose is obvious), and Ops could be smart enough to assign descriptions to parameters.

**Comment by dnault** [comment]
Hi, therapi-runtime-javadoc maintainer here. I'm glad to hear you're getting some mileage out of it.

Version 0.13.0 was recently released, with a fix for dnault/therapi-runtime-javadoc#57 (duplicate classes in `com.github.therapi.runtimejavadoc.repack.com.eclipsesource.json`). I think this might have affected you? 

If there are other things you'd like to see fixed or added, don't be shy about filing issues. I'll do my best to help out.

**Comment by ctrueden** [comment]
Thanks for the note, @dnault! And thanks for therapi—it's super useful for the scijava-ops project. As we get closer to release, we'll be in touch about anything we may need on the therapi side.
