### ISSUE TITLE
Review `RichOp` / `OpInstance` / `OpMetadata` API classes

### ISSUE THREAD

**Issue by ctrueden** [scijava/scijava#86]
Maybe `OpBuilder` should have convenience methods like `richFunction()` and `richComputer()`? Or: it could return `OP` where `<OP extends T & RichOp<T>>`, so the caller can assign to either. Then you wouldn't have to manually cast to `RichOp` after calling e.g. `.function()` on a built op. Not sure how much pain that would solve versus introduce, though.

**Comment by gselzer** [comment]
If we did this, we'd want to expose `RichOp` in the `OpEnvironment`. Do we even want to do that? The only problem is that `RichOp<T>` does not extend `T` (and `<T, OP extends T & RichOp<T>>` is illegal) so anyone who used that, and then wanted to call that Op, would not have the Op's functional method available. If we don't do that, we will have to cast the `OpEnvironment` returns to `RichOp`, and we will assume that all `OpEnvironment`s return `RichOp`s under the hood. I'm not sure we want to make that assumption.

**Comment by gselzer** [comment]
Plan of action:
* [ ] Figure out whether we can just remove the `OpMetadata` class entirely.
* [ ] If not, can we just merge it (and also maybe `RichOp`) into `OpInstance`?

**Comment by gselzer** [comment]
Closed with the merge of scijava/incubator#90
