### ISSUE TITLE
Consider whether InfoChainGenerator should be extensible

### ISSUE THREAD

**Issue by ctrueden** [scijava/scijava#87]
And if so: whether there is ever a possibility of multiple implementations handling the same scenario. As [written currently](https://github.com/scijava/incubator/pull/46#discussion_r763345469), an exception would be thrown in that case.

**Comment by gselzer** [comment]
> Consider whether `InfoChainGenerator` should be extensible

Yeah, I think it should be. Theoretically, if someone makes a new `OpInfo` implementation, we will want to make a new `InfoChainGenerator`. With that said, in scijava/incubator#90 we move `InfoChainGenerator` into SciJava Ops Engine, so it would be less exposed that way.

> As https://github.com/scijava/incubator/pull/46#discussion_r763345469, an exception would be thrown in that case.

That's a great point, we should fix that logic. I'd like to wait until scijava/incubator#90 is merged, though, to avoid conflicts.
