### ISSUE TITLE
Fix small issues and typos

### ISSUE THREAD

**Issue by ctrueden** [scijava/scijava#88]
* [x] https://github.com/scijava/incubator/pull/46#discussion_r761389351
* [x] https://github.com/scijava/incubator/pull/46#discussion_r761390446
* [x] https://github.com/scijava/incubator/pull/46#discussion_r761400169
* [x] https://github.com/scijava/incubator/pull/46#discussion_r761402169
* [x] https://github.com/scijava/incubator/pull/46#discussion_r761403457
* [x] https://github.com/scijava/incubator/pull/46#discussion_r761407577
* [x] https://github.com/scijava/incubator/pull/46#discussion_r761409125
* [x] https://github.com/scijava/incubator/pull/46#discussion_r761410618
* [x] https://github.com/scijava/incubator/pull/46#discussion_r761411121
* [x] https://github.com/scijava/incubator/pull/46#discussion_r761413322
* [x] https://github.com/scijava/incubator/pull/46#discussion_r761468793
* [x] https://github.com/scijava/incubator/pull/46#discussion_r761469601
* [x] https://github.com/scijava/incubator/pull/46#discussion_r761477176
* [x] https://github.com/scijava/incubator/pull/46#discussion_r761495267
* [x] https://github.com/scijava/incubator/pull/46#discussion_r763346570
* [x] https://github.com/scijava/incubator/pull/46#discussion_r763350294

**Comment by gselzer** [comment]
Looks like all of these issues were fixed a little while ago!
