### ISSUE TITLE
SciJava module+package review

### ISSUE THREAD

**Issue by gselzer** [scijava/scijava#91]
Before 1.0, we need to review the packaging/requiring of all created modules. This involves:

* Ensuring each module has only *one* focus
* Ensuring interfaces are exposed and implementations are not
* Consider the removal of unused/deprecated functionality

**Comment by ctrueden** [comment]
Does this issue include review of only the `scijava` layer modules? Or also the `imagej` ones?

**Comment by ctrueden** [comment]
This issue should wait until after scijava/incubator#90 is merged.

**Comment by gselzer** [comment]
This is no longer blocked @ctrueden @hinerm as that PR got merged

**Comment by gselzer** [comment]
@hinerm and I are both content with the current module structure, so we're going to say that this was completed by scijava/incubator#90
