### ISSUE TITLE
module-info.java-based ServiceLoader does not work for non-JPMS-modularized projects

### ISSUE THREAD

**Issue by ctrueden** [scijava/scijava#96]
If a downstream dependency is not JPMS-modularized—i.e. does not have a `module-info.java` declaring `requires org.scijava.discovery.Discoverer` or whatever, then the `new DefaultOpEnvironment()` does not discover any ops because `javax.service.ServiceLoader` finds no `Discoverer` implementations from the perspective of the non-modularized project. This is unfortunate because one of SciJava 3's explicit goals is to *not* impose JPMS on downstream code—only use it ourselves for the core components, and make it so that people who *do* use JPMS downstream reap the benefits, particularly clear communication regarding which packages are exported/public.

We need to figure out what to do about this. It might work to use the old-style `ServiceLoader` discovery mechanism in that case: i.e. put a `META-INF/services` folder in the relevant JAR files declaring their interface implementations. Testing needed to see: A) does this let non-modularized downstream code discover things; and B) does this work in harmony with the JPMS-based method without hosing things up? Assuming it works, we also need a way to ensure these two sources of truth (`module-info.java` and `META-INF/services`) stay in sync.

**Comment by hinerm** [comment]
I started work on this in [this branch](https://github.com/scijava/incubator/tree/imagej/imagej-ops-2/meta-inf-services).

Simply creating `META-INF` entries for all the things we are exposing to the `ServiceLoader` via `module-info.java` seems to work great for everything except `Op` and `OpWrapper`: these cause test failures and without them the matching process doesn't actually work.

**Comment by hinerm** [comment]
The issue was simply that `META-INF` has different syntax requirements than `module-info.java`: inner classes need to use a `$` separator instead of `.`.

The next step is to create a script that auto-generates the `META-INF` files from the `module-info.java`'s.

**Comment by gselzer** [comment]
@hinerm this is completed, yes?

**Comment by hinerm** [comment]
The automation is not complete but the original issue is resolved. I split off the automation to [its own issue](https://github.com/scijava/scijava/issues/132)
