### ISSUE TITLE
Test ops found on command line but not eclipse

### ISSUE THREAD

**Issue by hinerm** [scijava/scijava#98]
There are 12 Ops that are not found when running the [OpRegressionTest](https://github.com/scijava/incubator/blob/a245ba7e6a33241ec5d3d72e7c034b37791ab783/imagej/imagej-ops2/src/test/java/net/imagej/ops2/OpRegressionTest.java#L11-L15) in Eclipse, resulting in this failure:

![image](https://user-images.githubusercontent.com/1123809/196459166-7ab4f6d1-386e-47f2-996b-448f9785ba58.png)

The missing ops are:

```
+|Info:net.imagej.ops2.types.TypeExtractorTests.func@
+|Info:net.imagej.ops2.types.TypeExtractorTests.funcRandom@
+|Info:net.imagej.ops2.types.adapt.LiftComputersToRAITest.testOp2@
+|Info:net.imagej.ops2.types.adapt.LiftComputersToRAITest.testOp3@
+|Info:net.imagej.ops2.types.adapt.LiftComputersToRAITest.testOp4@
+|Info:net.imagej.ops2.types.adapt.LiftComputersToRAITest.testOp5@
+|Info:net.imagej.ops2.types.adapt.LiftComputersToRAITest.testOp@
+|Info:net.imagej.ops2.types.adapt.LiftFunctionsToRAITest.testOp2@
+|Info:net.imagej.ops2.types.adapt.LiftFunctionsToRAITest.testOp3@
+|Info:net.imagej.ops2.types.adapt.LiftFunctionsToRAITest.testOp4@
+|Info:net.imagej.ops2.types.adapt.LiftFunctionsToRAITest.testOp5@
+|Info:net.imagej.ops2.types.adapt.LiftFunctionsToRAITest.testOp@
```

This prompted me to go back and run the tests in `scijava-discovery-therapi` and confirm that they do indeed also fail when run from Eclipse:

![image](https://user-images.githubusercontent.com/1123809/196472428-e5897fa7-19e3-462b-9676-ffa0c46aa82c.png)

![image](https://user-images.githubusercontent.com/1123809/196472716-179ed46c-babf-4023-b7bf-49c90a6daabe.png)

**Comment by hinerm** [comment]
Yeah for sure it's not seeing `target/test-classes` on the classpath... classpath as of [this line](https://github.com/scijava/incubator/blob/a245ba7e6a33241ec5d3d72e7c034b37791ab783/scijava/scijava-discovery-therapi/src/main/java/org/scijava/discovery/therapi/TherapiDiscoverer.java#L117)

```
[C:\Users\hiner\code\scijava\incubator\scijava\scijava-common3\target\classes, C:\Users\hiner\.m2\repository\org\junit\jupiter\junit-jupiter-api\5.7.1\junit-jupiter-api-5.7.1.jar, C:\Users\hiner\.m2\repository\org\apiguardian\apiguardian-api\1.1.0\apiguardian-api-1.1.0.jar, C:\Users\hiner\.m2\repository\org\opentest4j\opentest4j\1.2.0\opentest4j-1.2.0.jar, C:\Users\hiner\.m2\repository\org\junit\platform\junit-platform-commons\1.7.1\junit-platform-commons-1.7.1.jar, C:\Users\hiner\.m2\repository\org\junit\jupiter\junit-jupiter-engine\5.7.1\junit-jupiter-engine-5.7.1.jar, C:\Users\hiner\.m2\repository\org\junit\platform\junit-platform-engine\1.7.1\junit-platform-engine-1.7.1.jar, C:\Users\hiner\.m2\repository\org\junit\platform\junit-platform-launcher\1.7.1\junit-platform-launcher-1.7.1.jar, C:\Users\hiner\eclipse\java-2022-09\eclipse\configuration\org.eclipse.osgi\227\0\.cp, C:\Users\hiner\eclipse\java-2022-09\eclipse\configuration\org.eclipse.osgi\225\0\.cp]
```

**Comment by hinerm** [comment]
Comparison of `paths` at [this line](https://github.com/scijava/incubator/blob/a245ba7e6a33241ec5d3d72e7c034b37791ab783/scijava/scijava-discovery-therapi/src/main/java/org/scijava/discovery/therapi/TherapiDiscoverer.java#L118) in Eclipse and IntelliJ (red boxes contain classpath entries, while remaining are modulepath):

![image](https://user-images.githubusercontent.com/1123809/196984156-4837b7af-7010-4002-9670-52ea869c8278.png)

**Comment by hinerm** [comment]
TODO: is this still currently an issue with the meta-inf generation and changes to op harvesting? Maybe we can just close it? Or make it clear that IntelliJ is recommended and punt to paper 3

**Comment by ctrueden** [comment]
@hinerm will test whether/how this behaves now after scijava/incubator#79 happens.

**Comment by hinerm** [comment]
> @hinerm will test whether/how this behaves now after [scijava/incubator#79](https://github.com/scijava/incubator/pull/79) happens.

Tests pass now!
